passage: we should always be in PASSAGE_DIR, so just use ./

diff --git a/passage.in b/passage.in
--- a/passage.in
+++ b/passage.in
@@ -52,12 +52,10 @@ encrypt() {
 
 is_beneath_store() {
     while [ "$#" -gt 0 ]; do
-        path=$(printf '%s' "${1}" | sed -E 's|^/+||')
-
         case "$(readlink -f "${PASSAGE_DIR}"/"${1}")" in
             "${PASSAGE_DIR}"/*|"${PASSAGE_DIR}") : ;;
             *)
-                printf 'error: path "%s" is not within the password store\n' "${path}" >&2
+                printf 'error: path "%s" is not within the password store\n' "${1}" >&2
                 exit 4
                 ;;
         esac
@@ -85,10 +83,10 @@ EOF
 pretty_list() {
     [ "$#" -eq 0 ] && set -- .
     while [ $# -gt 0 ]; do
-        find "${1}" -type d \( -not -name '.*' \) | sed -E 's|$|/|; s|/+$|/|'
-        find "${1}" \( -type f -name '*.age' \)
+        find ./"${1}" -type d \( -not -name '.*' \) | sed -E 's|$|/|; s|/+$|/|'
+        find ./"${1}" \( -type f -name '*.age' \)
         shift
-    done | sed 's|\.age$||; s|^\./||' | sort -d
+    done | sed -E 's|\.age$||; s|^(\./)+||g' | sort -d
 }
 
 ## Modes
@@ -119,7 +117,7 @@ passage_convert() {
     # Temporary enable path globbing.
     set +f
     while [ $# -gt 0 ]; do
-        cp -r "$1"/* "${PASSAGE_DIR}"
+        cp -r "$1"/* ./
         shift
     done
     set -f
@@ -130,7 +128,7 @@ passage_convert() {
     # shellcheck disable=SC2086
     find . -name '*.gpg' -type f -not -type l | while read -r file; do
         "${verbose}" && printf '%s\n' "${file}" >&2
-        gpg ${gpg_args} --batch -d "${file}" | encrypt > "${file%.gpg}.age"
+        gpg ${gpg_args} --batch -d "${file}" | encrypt > ./"${file%.gpg}.age"
         rm -f "${file}"
     done
 
@@ -139,7 +137,7 @@ passage_convert() {
         new_link=$(readlink "${name}")
         new_link="${new_link%.gpg}".age
         new_name="${name%.gpg}".age
-        ln -sf "${new_link}" "${new_name}"
+        ln -sf "${new_link}" ./"${new_name}"
         rm -f "${name}"
     done
 }
@@ -151,7 +149,7 @@ passage_edit() {
         temp=$(mktemp "${TMPDIR}"/passage.XXXXXX)
         chmod 700 "${temp}"
 
-        [ -f "${PASSAGE_DIR}"/"${1}".age ] && decrypt "${1}".age > "${temp}"
+        [ -f ./"${1}".age ] && decrypt ./"${1}".age > "${temp}"
 
         "${EDITOR:-vi}" "${temp}" || {
             printf \
@@ -159,7 +157,7 @@ passage_edit() {
             rm -f "${temp}"
         }
 
-        encrypt "${temp}" > "${PASSAGE_DIR}"/"${1}".age
+        encrypt "${temp}" > ./"${1}".age
         rm -f "${temp}"
 
         shift
@@ -197,14 +195,14 @@ passage_generate() {
     while [ $# -gt 0 ]; do
         is_beneath_store "$1"
 
-        if [ -e "${PASSAGE_DIR}"/"${1}" ] && ! "${clobber}"; then
+        if [ -e ./"${1}" ] && ! "${clobber}"; then
             printf \
                 'error: password file "%s" already exists, refusing to clobber without -f\n' \
                 "${1}" >&2
             exit 2
         fi
 
-        [ -d "${PASSAGE_DIR}"/"${1%/*}" ] || {
+        [ -d ./"${1%/*}" ] || {
             printf \
                 'error: password directory "%s" does not exist\n' \
                 "${1}" >&2
@@ -213,7 +211,7 @@ passage_generate() {
 
         # NOTE: Using bs="${length}" count=1 rather than bs=1 count="${length}" saves syscalls.
         LC_ALL=C tr -cd '[:alnum:][:punct:]' </dev/urandom \
-            | dd bs="${length}" count=1 2>/dev/null | encrypt > "${PASSAGE_DIR}"/"${1}".age
+            | dd bs="${length}" count=1 2>/dev/null | encrypt > ./"${1}".age
 
         shift
     done
@@ -243,23 +241,23 @@ passage_show() {
 
     shift $(( OPTIND - 1 ))
 
-    if [ -d "${1}" ] || [ -z "${1}" ]; then
+    if [ -d ./"${1}" ] || [ -z "${1}" ]; then
         pretty_list "$@"
         return $?
     fi
 
-    is_beneath_store "$1".age
+    is_beneath_store "${1}".age
 
-    if [ -f "${PASSAGE_DIR}"/"${1}".age ]; then
+    if [ -f ./"${1}".age ]; then
         if "${copy}"; then
-            decrypt "${PASSAGE_DIR}"/"${1}".age | xsel -ib
+            decrypt ./"${1}".age | xsel -ib
             printf 'Password copied to clipboard. Clipboard will be cleared in 45 seconds.\n' >&2
             (
                 sleep 45
                 xsel -cb
             ) &
         else
-            decrypt "${PASSAGE_DIR}"/"${1}".age
+            decrypt ./"${1}".age
         fi
     else
         printf 'error: password file "%s" does not exist\n' "${1}" >&2
@@ -297,9 +295,9 @@ passage_cp() {
     is_beneath_store "$1"
 
     if [ -d "${1}" ]; then
-        cp ${force:+-f} ${recurse:+-r} "${PASSAGE_DIR}"/"$1" "${PASSAGE_DIR}"/"$2"
+        cp ${force:+-f} ${recurse:+-r} ./"$1" ./"$2"
     else
-        cp ${force:+-f} ${recurse:+-r} "${PASSAGE_DIR}"/"$1".age "${PASSAGE_DIR}"/"$2".age
+        cp ${force:+-f} ${recurse:+-r} ./"$1".age ./"$2".age
     fi
 }
 
@@ -327,9 +325,9 @@ passage_ln() {
     is_beneath_store "$@"
 
     if [ -d "${1}" ]; then
-        ln -s ${force:+-f} "$1" "${PASSAGE_DIR}"/"$2"
+        ln -s ${force:+-f} "$1" ./"$2"
     else
-        ln -s ${force:+-f} "$1".age "${PASSAGE_DIR}"/"$2".age
+        ln -s ${force:+-f} "$1".age ./"$2".age
     fi
     shift
 }
@@ -353,7 +351,7 @@ passage_mkdir() {
     is_beneath_store "$@"
 
     while [ $# -gt 0 ]; do
-        mkdir ${parents:+-p} "${PASSAGE_DIR}"/"${1}"
+        mkdir ${parents:+-p} ./"${1}"
 
         shift
     done
@@ -382,12 +380,12 @@ passage_mv() {
 
     is_beneath_store "$@"
 
-    if [ -d "${PASSAGE_DIR}"/"${1}" ] && [ -d "${PASSAGE_DIR}"/"${2}" ]; then
-        mv ${force:+-f} "${PASSAGE_DIR}"/"$1" "${PASSAGE_DIR}"/"$2"
-    elif [ -e "${PASSAGE_DIR}"/"${1}" ] && [ -d "${PASSAGE_DIR}"/"${2}" ]; then
-        mv ${force:+-f} "${PASSAGE_DIR}"/"$1".age "${PASSAGE_DIR}"/"$2"
+    if [ -d ./"${1}" ] && [ -d ./"${2}" ]; then
+        mv ${force:+-f} ./"$1" ./"$2"
+    elif [ -e ./"${1}" ] && [ -d ./"${2}" ]; then
+        mv ${force:+-f} ./"$1".age ./"$2"
     else
-        mv ${force:+-f} "${PASSAGE_DIR}"/"$1".age "${PASSAGE_DIR}"/"$2".age
+        mv ${force:+-f} ./"$1".age ./"$2".age
     fi
 }
 
@@ -415,9 +413,9 @@ passage_rm() {
         is_beneath_store "$1"
 
         if [ -d "${1}" ]; then
-            rm ${force:+-f} ${recurse:+-r} "${PASSAGE_DIR}"/"$1"
+            rm ${force:+-f} ${recurse:+-r} ./"$1"
         else
-            rm ${force:+-f} ${recurse:+-r} "${PASSAGE_DIR}"/"$1".age
+            rm ${force:+-f} ${recurse:+-r} ./"$1".age
         fi
 
         shift
@@ -453,7 +451,6 @@ case "${mode}" in
         }
 
         cd "${PASSAGE_DIR}"
-
         ;;
 esac
 
